#!/bin/sh
# Setup a machine for Sublime Text 2
set -x

ln -s "/opt/homebrew-cask/Caskroom/sublime-text/2.0.1/Sublime\ Text\ 2.app/Contents/SharedSupport/bin/subl" "$ZSH/bin/subl"

# symlink settings in
sublime_dir=~/Library/Application\ Support/Sublime\ Text\ 2/Packages
mv "$sublime_dir/User" "$sublime_dir/User.backup"
ln -s "$ZSH/sublime2/User" "$sublime_dir"

# Grab the Soda theme
cd "$sublime_dir"
git clone https://github.com/buymeasoda/soda-theme/ "Theme - Soda"
